import numpy as np
from numpy.typing import NDArray

class FeatureExtractor:
    def __init__(self, sample_rate: int) -> None: ...
    @property
    def frame_size(self) -> int: ...
    @property
    def hann_window(self) -> NDArray[np.float32]: ...
    def extract_features(self, audio: NDArray[np.float32]) -> NDArray[np.float32]: ...
